
export const MOCK_STATIONS = [
  'Kigali (Nyabugogo)',
  'Kigali (Remera)',
  'Kigali (Gikondo)',
  'Kigali (Nyamirambo)',
  'Musanze (Ruhengeri)',
  'Rubavu (Gisenyi)',
  'Huye (Butare)',
  'Rusizi (Cyangugu)',
  'Rwamagana',
  'Nyagatare',
  'Muhanga (Gitarama)',
  'Nyamata (Bugesera)',
  'Karongi (Kibuye)',
  'Kayonza',
  'Kibungo',
  'Gicumbi (Byumba)',
  'Ruhango',
  'Nyanza',
  'Ngororero',
  'Nyabihu',
  'Rutsiro',
  'Nyamasheke',
  'Nyamagabe',
  'Nyaruguru',
  'Kamonyi',
  'Gakenke',
  'Burera',
  'Rulindo',
  'Gatsibo',
  'Kirehe',
  'Ngoma',
];

export const BUS_PARKS = [
  'Nyabugogo Bus Terminal',
  'Remera Bus Station',
  'Musanze International Park',
  'Rubavu Main Park',
  'Huye Taxi Park',
  'Muhanga Bus Station',
  'Rusizi Border Park',
  'Rwamagana Main Station',
  'Nyagatare Bus Park',
  'Nyamata Taxi Park',
  'Karongi Bus Terminal',
  'Kayonza Junction Park',
  'Kibungo Station',
  'Gicumbi Modern Park',
  'Nyanza Bus Station',
  'Ruhango Market Park',
  'Nyamagabe Bus Park',
  'Gisenyi Border Post',
];

export const TRANSPORT_COMPANIES = [
  'Move (Ride)',
  'Volcano Express',
  'Ritco',
  'Horizon Express',
  'Stella Express',
  'Jaguar Executive',
  'Royal Express',
  'Express Motors',
  'Omega Express',
  'Sotra',
  'Matunda Express',
];
